name = "aztracker-bot"
main = "worker.js"
compatibility_date = "2026-05-17"

[[kv_namespaces]]
binding = "AZTRACKER_DB"
id = "YOUR_CF_NAMESPACE_ID_HERE"

[vars]
GITHUB_OWNER = "aka-khalid"
GITHUB_REPO = "AzTracker"
ALLOWED_USERS = "760872964"
