name = "aztracker-bot"
main = "worker.js"
compatibility_date = "2026-05-23"

[[kv_namespaces]]
binding = "AZTRACKER_DB"
id = "90fcfcb742fe4d7299087c076bd1ba4d"

[vars]
GITHUB_OWNER = "aka-khalid"
GITHUB_REPO = "AzTracker"
DEFAULT_USER_PRODUCT_LIMIT = "5"
GLOBAL_POOL_LIMIT = "450"

